trigger:
  branches:
    include:
      - tests

pool:
  name:  'Test'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Instala las dependencias necesarias'

- script: |
    npm run test
  displayName: 'Ejecutando los tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-reports/*.xml'
    failOnBadExitCode: true
  displayName: 'Publicar resultados de pruebas'

- task: Bash@3
  condition: succeeded()
  inputs:
    targetType: 'inline'
    script: |
      echo "Los test pasaron"
      git config --global user.name "deyvigo"
      git config --global user.email "deyvi.gomez@unmsm.edu.pe"

      # Agregar remoto para GitHub
      git remote remove github || true
      git remote add github https://deyvigo:$(GITHUB_TOKEN)@github.com/deyvigo/azure-test-app.git

      # Traer los últimos cambios del remoto y fusionarlos
      git fetch github
      git pull github tests --rebase || git pull github tests --no-rebase || true

      # Asegurarse de que estamos en la rama correcta
      git checkout tests || git checkout -b tests

      # Agregar y hacer commit de los cambios locales
      git add .
      git commit -m "Sync local branch with remote"

      # Forzar el push para sincronizar con el remoto
      git push github tests --force-with-lease
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
