trigger:
  branches:
    include:
      - tests

pool:
  name:  'Test'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Instala las dependencias necesarias'

- script: |
    npm run test
  displayName: 'Ejecutando los tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-reports/*.xml'
    failOnBadExitCode: true
  displayName: 'Publicar resultados de pruebas'
